# Generated by Django 3.2.8 on 2021-10-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='document',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='user',
        ),
        migrations.DeleteModel(
            name='Approval',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Pending',
        ),
        migrations.AlterField(
            model_name='academic_manpower',
            name='faculty',
            field=models.ManyToManyField(null=True, to='data.Faculty'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='faculty',
            field=models.ManyToManyField(null=True, to='data.Faculty'),
        ),
        migrations.AlterField(
            model_name='event',
            name='faculty',
            field=models.ManyToManyField(null=True, to='data.Faculty'),
        ),
    ]
