# Generated by Django 3.2.8 on 2021-10-25 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20211025_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_request_evaluate', models.DateField()),
                ('date_evaluate', models.DateField()),
                ('date_begin', models.DateField()),
                ('date_full_term', models.DateField()),
                ('position_rc', models.CharField(max_length=255)),
                ('situation', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Author', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_evaluate', models.DateField()),
                ('date_expire', models.DateField()),
                ('level_evaluate_tech', models.CharField(max_length=255)),
                ('level_evaluate_document', models.CharField(max_length=255)),
                ('no_evaluate', models.IntegerField()),
                ('faculty', models.ManyToManyField(null=True, to='data.Faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('อนุมัติ', 'อนุมัติ'), ('ไม่อนุมัติ', 'ไม่อนุมัติ')], max_length=10)),
                ('position', models.CharField(max_length=255)),
                ('faculty_academic', models.CharField(max_length=255)),
                ('date_request', models.DateField()),
                ('date_approval', models.DateField()),
                ('document', models.TextField()),
                ('publicity', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
