# Generated by Django 3.2.8 on 2021-10-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20211023_1047'),
        ('data', '0003_approval_document_pending'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.AlterField(
            model_name='academic_manpower',
            name='faculty',
            field=models.ManyToManyField(null=True, to='account.Faculty'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='faculty',
            field=models.ManyToManyField(null=True, to='account.Faculty'),
        ),
        migrations.AlterField(
            model_name='document',
            name='faculty',
            field=models.ManyToManyField(null=True, to='account.Faculty'),
        ),
        migrations.AlterField(
            model_name='event',
            name='faculty',
            field=models.ManyToManyField(null=True, to='account.Faculty'),
        ),
    ]
